theme: jekyll-theme-minimal
minimal_mistakes_skin: "contrast"
title: R.Cepeda Su치rez
description: 
markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jemoji
show_downloads: false
github:
  is_project_page: true

languages: 
  - en
  - es
default_lang: en

# Definici칩n de navegaci칩n (sin duplicaci칩n)
nav:
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Photography"
    url: "/photo/"
