theme: jekyll-theme-minimal
minimal_mistakes_skin: "contrast"
title: L. Guillermo Woo Mora
description: 
markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jemoji
show_downloads: false
github:
  is_project_page: true

languages: 
  - en
  - sp
default_lang: en
exclude_from_localization:
  - "CV.pdf"  # Aquí puedes excluir archivos que no necesitan traducción
